### PR TITLE
Added CustomUrlCategory object type to objects.py

### PR DESCRIPTION
**Pull request by ngobert**
Resolves enhancement request #129 .

### CODE REVIEW

**Comment by haginara** [comment]
I need this updating. FYI, codes are exactly same that I am using with modifying.

**Comment by ngobert** [comment]
This pull request has been outstanding for a while now.  Is there anything that I need to work on specifically to get it reviewed and approved?

**Comment by ngobert** [comment]
@shinmog 
See requested additions as child to device group / firewall / vsys.  I didn't make any changes to Panorama, as none of the current objects are direct children of Panorama (although it seems like maybe they should be for "shared" objects that aren't tied to a specific device group?).

Let me know if you have any further suggestions/questions.

**Comment by shinmog** [comment]
@ngobert 

The code itself looks good now, but your commit history is including stuff that I've committed a while back.  Please just rebase this against develop to clean up the commit history so I can merge this.

Thanks for your hard work!

**Comment by ngobert** [comment]
@shinmog 

Sorry about that -- I've squashed it down to a single commit and re-based to current develop branch.

**Pull request merged**
