### PR TITLE
Bring Python current in Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@PaloAltoNetworks @shinmog please review

**Comment by btorresgil** [comment]
This looks good. However, we’re switching from Travis to GitHub Action imminently. I can merge it but then we’ll remove the file soon.

**Comment by gliptak** [comment]
@btorresgil let me know if you are interested in a Github build PR

**Comment by btorresgil** [comment]
@gliptak Thanks for the offer. I created a PR for GitHub Actions here: https://github.com/PaloAltoNetworks/pandevice/pull/214

It's missing python 3.8 due to an issue I'm troubleshooting, but I'll add py3.8 shortly after merge. Open to a review if you're up for it!

**Pull request merged**
